# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabBar::tab\n"
"{\n"
"    width: 50ex;\n"
"    height: 12ex;\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.tabWidget.addTab(self.tab_users, "Utilisateurs")
        self.tab_roles = QtWidgets.QWidget()
        self.tab_roles.setObjectName("tab_roles")
        self.tabWidget.addTab(self.tab_roles, "")
        self.tab_interests = QtWidgets.QWidget()
        self.tab_interests.setObjectName("tab_interests")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_interests)
        self.timeEdit.setGeometry(QtCore.QRect(260, 130, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.tabWidget.addTab(self.tab_interests, "")
        self.tab_conversation = QtWidgets.QWidget()
        self.tab_conversation.setObjectName("tab_conversation")
        self.tabWidget.addTab(self.tab_conversation, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_roles), _translate("MainWindow", "Rôles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_interests), _translate("MainWindow", "Intérêts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conversation), _translate("MainWindow", "Discussions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
